FROM node:22-alpine AS builder

WORKDIR /app

COPY ./ ./

RUN npm install
RUN npm run build

FROM node:22-alpine AS runner

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY package*.json ./

RUN npm install --only=production

CMD node dist/index.js

